corner-radius = 10;

shadow = true;
shadow-radius = 12;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-opacity = 0.22;

inactive-opacity = 0.96;
active-opacity = 1.0;

fading = true;
fade-in-step = 0.12;
fade-out-step = 0.03;
fade-delta = 4;

blur-method = "dual_kawase";
blur-strength = 3;
blur-background = false;

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Conky'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Cairo-clock'",
  "window_type = 'dock'",
  "_GTK_FRAME_EXTENTS@:c",
  "class_g = 'firefox'",
  "class_g = 'firefox' && (window_type = 'utility' || window_type = 'popup_menu')"
];

blur-background-exclude = [
  "window_type = 'dock'",
  "class_g = 'xfce4-panel'",
  "class_g = 'Plank'",
  "class_g = 'firefox'",
  "class_g = 'Navigator'",
  "_GTK_FRAME_EXTENTS@:c"
];